Lesson 1 6
jalvarado9000/react-todo pull request #6
Opened 2024-04-01 02:03 UTC by jalvarado9000

Changes made on the file include, InputWithLabel.jsx was created to be reusable, section of any form. Used children, isFocused props. Refactor code to put InputWithLabel as a open/close tag, instead of a self closing one to use children prop. Added button to TODO LIST to remove list items the user doesn't want to see anymore. Updated UseEffect and localStorage section  of APP.jsx to also watch out if the key changes to re load the list and update it accordantly. The page also uses UseEffect and autoFocus on the  InputWithLabel.jsx  text input to autoFocus, that sections when the page is updated.

2024-04-02 17:40 UTC, e-spitz requested changes
Local storage worked great for me! Really nice job adding that along with the `useRef` hook! I'd like to see a couple of changes here before I approve. Let me know if you have any questions about my comments!

2024-04-02 17:40 UTC, e-spitz commented on src/InputWithLabel.jsx
> +import React from 'react'
`import { useEffect, useRef } from 'react'`

2024-04-02 17:40 UTC, e-spitz commented on src/InputWithLabel.jsx
> +            <input ref={inputRef} name={children} type="text" id={todoTitle} value={todoTitle} onChange={handleTitleChange} />
With so many attributes belonging to this `input` element, you could clean it up and make it more readable by putting the attributes on separate lines! =)

Have you looked to see what the value of `children` is here?

2024-04-02 17:40 UTC, e-spitz commented on src/InputWithLabel.jsx
> +    const inputRef = React.useRef();
By destructuring the imports like suggested on line1, you can remove the `React.` here

2024-04-02 17:40 UTC, e-spitz commented on src/InputWithLabel.jsx
> +    React.useEffect(() => {
Can also remove it from here as well!

2024-04-02 17:40 UTC, e-spitz commented on src/AddTodoForm.jsx
>  import React, { useState } from 'react';
You can remove `React` here

2024-04-02 17:40 UTC, e-spitz commented on src/InputWithLabel.jsx
> +                Title
I think we are looking to have a dynamic `{label}` here instead of hard coding `Title`. How would you go about doing this?

2024-04-02 17:40 UTC, e-spitz commented on src/AddTodoForm.jsx
> +        <InputWithLabel todoTitle={todoTitle} handleTitleChange={handleTitleChange} isFocused> title </InputWithLabel>
On line 18, great destructuring! But it looks like those variables aren't actually being used in the code, so it's best practice to remove those for now.

2024-04-02 17:40 UTC, e-spitz commented on src/InputWithLabel.jsx
> +            <label htmlFor={todoTitle} className="h5 m-1 mt-3">
Is the `h5` here being used for text size? Is there an alternative way for you to accomplish this?

2024-04-02 22:26 UTC, jalvarado9000 commented on src/InputWithLabel.jsx
> +            <input ref={inputRef} name={children} type="text" id={todoTitle} value={todoTitle} onChange={handleTitleChange} />
yes, in this case it would be 'title' since its hard coded

2024-04-03 01:36 UTC, jalvarado9000 commented on src/InputWithLabel.jsx
> +            <label htmlFor={todoTitle} className="h5 m-1 mt-3">
yes, but i want to focus my time more learning react rather than decorating the page plus I want to practice Bootstrap.

2024-04-03 01:39 UTC, jalvarado9000 commented on src/InputWithLabel.jsx
> +                Title
ok got it.

2024-04-03 01:42 UTC, jalvarado9000 commented on src/InputWithLabel.jsx
> +            <label htmlFor={todoTitle} className="h5 m-1 mt-3">
m-1 is changing the margin from top, bottom, left and right. mt-3 is margin top. the numbers go from 1-5 in size.

2024-04-04 18:16 UTC, e-spitz commented on src/InputWithLabel.jsx
> +            <input ref={inputRef} name={children} type="text" id={todoTitle} value={todoTitle} onChange={handleTitleChange} />
With the assignment, is it supposed to be hard-coded or dynamic?

2024-04-07 00:40 UTC, merged